"""empty message

Revision ID: 5bac0f7444f9
Revises: 976e95388e06
Create Date: 2020-12-20 14:51:28.369401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bac0f7444f9'
down_revision = '976e95388e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city_state', sa.Integer(), nullable=True))
    op.drop_constraint('Venue_area_state_city_fkey', 'Venue', type_='foreignkey')
    op.create_foreign_key(None, 'Venue', 'area', ['city_state'], ['id'])
    op.drop_column('Venue', 'area_state_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_state_city', sa.INTEGER(), autoincrement=False, nullable=True))
   
    op.create_foreign_key('Venue_area_state_city_fkey', 'Venue', 'area', ['area_state_city'], ['id'])
    op.drop_column('Venue', 'city_state')
    # ### end Alembic commands ###
