"""empty message

Revision ID: 5d3e07be7569
Revises: 5bac0f7444f9
Create Date: 2020-12-20 15:06:37.669410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3e07be7569'
down_revision = '5bac0f7444f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_id', sa.Integer(), nullable=True))
    op.drop_constraint('Venue_area_state_city_fkey', 'Venue', type_='foreignkey')
    op.create_foreign_key(None, 'Venue', 'area', ['area_id'], ['id'])
    op.drop_column('Venue', 'area_state_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_state_city', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.create_foreign_key('Venue_area_state_city_fkey', 'Venue', 'area', ['area_state_city'], ['id'])
    op.drop_column('Venue', 'area_id')
    # ### end Alembic commands ###
