"""empty message

Revision ID: 874c0f9bdd1d
Revises: 5d3e07be7569
Create Date: 2020-12-20 16:11:55.754670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874c0f9bdd1d'
down_revision = '5d3e07be7569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    op.add_column('Venue', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_constraint('Venue_area_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_area_id_fkey', 'Venue', 'area', ['area_id'], ['id'])
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'city')
    op.create_table('area',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='area_pkey')
    )
    # ### end Alembic commands ###
