"""empty message

Revision ID: e577cc2e8086
Revises: 874c0f9bdd1d
Create Date: 2020-12-20 16:29:33.255155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e577cc2e8086'
down_revision = '874c0f9bdd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'area_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###
